spring:
  application:
    name: transfer-service

  datasource:
    url: jdbc:mysql://localhost:3306/transfer?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: application
    password: application
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  h2:
    console:
      enabled: false

server:
  port: 8080

# Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs

